// SplitNow database types
// Mirror of the schema in supabase/schema.sql + 02_auth_rls.sql.

export type AvatarColor = 'green' | 'blue' | 'purple' | 'orange';

export type SubscriptionPlan   = 'free' | 'pro' | 'teams';
export type SubscriptionStatus = 'active' | 'trialing' | 'past_due' | 'canceled' | 'expired';

export interface User {
  id: string;
  /** Null until the user completes the profile-setup screen after OTP. */
  name: string | null;
  phone: string | null;
  upi_id: string | null;
  avatar_color: AvatarColor;
  /** 8-char unique invite code, generated by DB on first insert. */
  invite_code: string | null;
  created_at: string;
  // ── Subscription ──────────────────────────────────────────────────────────
  subscription_plan:    SubscriptionPlan;
  subscription_status:  SubscriptionStatus;
  /** UTC timestamp when the current paid period ends. Null for free plan. */
  subscription_period_end:  string | null;
  /** UTC timestamp when any active trial ends. */
  trial_end:                string | null;
  razorpay_customer_id:     string | null;
  razorpay_subscription_id: string | null;
}

export interface Group {
  id: string;
  name: string;
  created_by: string | null;
  created_at: string;
}

export interface GroupMember {
  group_id:  string;
  user_id:   string;
  joined_at: string;
}

export type ExpenseType = 'group' | 'personal' | 'advance';

export interface Expense {
  id:         string;
  group_id:   string;
  title:      string;
  amount:     number;
  category:   string;
  type:       ExpenseType;
  paid_by:    string | null;
  added_by:   string | null;
  note:       string | null;
  created_at: string;
  updated_at: string | null;
}

export interface ExpenseSplit {
  id:          string;
  expense_id:  string;
  user_id:     string;
  amount_owed: number;
}

export interface ExpenseComment {
  id:         string;
  expense_id: string;
  user_id:    string;
  parent_id:  string | null;
  text:       string;
  created_at: string;
}

export interface Friendship {
  id: string;
  /** Always the lexicographically smaller UUID of the pair. */
  user_id: string;
  friend_id: string;
  created_at: string;
}

export type SettlementStatus = 'pending' | 'completed' | 'failed';

export interface Settlement {
  id:         string;
  group_id:   string | null;
  from_user:  string | null;
  to_user:    string | null;
  amount:     number;
  status:     SettlementStatus;
  upi_ref:    string | null;
  settled_at: string;
}

// Computed: per-counterparty net for the current user.
// Positive amount = they owe you. Negative = you owe them.
export interface Balance {
  userId: string;
  name: string;
  amount: number;
  upiId: string | null;
  avatarColor: AvatarColor;
}

// Insert payloads (everything DB-generated is optional)
export type UserInsert       = Omit<User, 'id' | 'created_at'>                        & Partial<Pick<User, 'id' | 'created_at'>>;
export type GroupInsert      = Omit<Group, 'id' | 'created_at'>                       & Partial<Pick<Group, 'id' | 'created_at'>>;
export type ExpenseInsert    = Omit<Expense, 'id' | 'created_at' | 'updated_at' | 'type'> & Partial<Pick<Expense, 'id' | 'created_at' | 'updated_at' | 'type'>>;
export type SplitInsert      = Omit<ExpenseSplit, 'id'>                               & Partial<Pick<ExpenseSplit, 'id'>>;
export type CommentInsert    = Omit<ExpenseComment, 'id' | 'created_at' | 'parent_id'> & Partial<Pick<ExpenseComment, 'id' | 'created_at' | 'parent_id'>>;
export type SettlementInsert = Omit<Settlement, 'id' | 'settled_at' | 'status'>       & Partial<Pick<Settlement, 'id' | 'settled_at' | 'status'>>;

// Database type consumed by `createClient<Database>` in lib/supabase.ts.
//
// `Database['public']` must satisfy postgrest-js's `GenericSchema`:
//   { Tables: Record<string, GenericTable>; Views: ...; Functions: ... }
// and each Table must have `{ Row, Insert, Update, Relationships }`.
// Without the Views/Functions stubs *and* Relationships on every table, the
// Schema generic collapses to `never` and every `.from('x').insert(...)` call
// type-checks against `never` — that's the source of the "argument of type X
// is not assignable to parameter of type 'never'" errors.
type Tbl<R, I, U = Partial<R>> = { Row: R; Insert: I; Update: U; Relationships: [] };

export interface Database {
  public: {
    Tables: {
      users:             Tbl<User,           UserInsert>;
      groups:            Tbl<Group,          GroupInsert>;
      group_members:     Tbl<GroupMember,    GroupMember>;
      expenses:          Tbl<Expense,        ExpenseInsert>;
      expense_splits:    Tbl<ExpenseSplit,   SplitInsert>;
      expense_comments:  Tbl<ExpenseComment, CommentInsert>;
      settlements:       Tbl<Settlement,     SettlementInsert>;
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
}
